### ISSUE TITLE
[v13] importEd25519Seed doesn't work as expected

### ISSUE THREAD

**Issue by AyushBherwani1998** [tkey/tkey#285] opened 2024-06-24 05:55 UTC
## Description 
When trying to initialize the tKey with importEd25519Seed parameter. Ideally it should use the seed and import the account in tKey as per my understanding of the usage. The address generated is different, I checked the seed using the retriveEd25519Seed method, and the seed is not the same which I passed in importEd25519Seed parameter during the initalization. 

## Reproducible step
You can use this example and uncomment the `importEd25519Seed` in initialization. 
Example: https://github.com/tkey/tkey-examples/pull/84

**Comment by AyushBherwani1998** [comment] 2024-06-25 05:58
@matthiasgeihs works fine in alpha-v7, able to get the same address when using importEd25519Seed. On the side note, when I already have an account, and I'm using the importEd25519 it doesn't work which is intended. But should we throw an error saying, the account already exist or something similar?

**Comment by matthiasgeihs** [comment] 2024-06-25 06:24
I'm not super familiar with these flows. Probably @ieow can comment here. What is the intended flow for when we import ed25519 key for an existing account?

**Comment by himanshuchawla009** [comment] 2024-07-01 05:33
> @matthiasgeihs works fine in alpha-v7, able to get the same address when using importEd25519Seed. On the side note, when I already have an account, and I'm using the importEd25519 it doesn't work which is intended. But should we throw an error saying, the account already exist or something similar?

**Comment by himanshuchawla009** [comment] 2024-07-01 05:35
> @matthiasgeihs works fine in alpha-v7, able to get the same address when using importEd25519Seed. On the side note, when I already have an account, and I'm using the importEd25519 it doesn't work which is intended. But should we throw an error saying, the account already exist or something similar?

Lets create a seperate issue to address this, i m closing this one as the working is confirmed

**Closed by himanshuchawla009** 2024-07-01 05:35 UTC
